### ISSUE TITLE
Wrong handling of AutoIncrement for PostgreSQL

### ISSUE THREAD

**Issue by reygoch** [valderman/selda#58]
I have the following code:

```
data User = User
  { id :: ID User
  , admin :: Bool

  , username :: Text
  , password :: Text

  , dateCreated :: UTCTime
  , dateModified :: UTCTime
  } deriving ( Eq, Show, Generic )

g_user :: GenTable User
g_user = genTable "User"
  [ ( id :: User -> ID User ) :- autoPrimaryGen
  ]
```

When I try to insert new user into that table I get this error message:

```
*** Exception: SqlError "error executing query `INSERT INTO \"User\" (\"id\", \"admin\", \"username\", \"password\", \"dateCreated\", \"dateModified\") VALUES (DEFAULT, $1, $2, $3, $4, $5)': ERROR:  null value in column \"id\" violates not-null constraint\nDETAIL:  Failing row contains (null, t, reygoch, $2y$14$daB6zQcjAbQRIys9k1QnI.I4JABb28J1F4KI0iFLM780jBjaP1q5m, 2017-12-22 19:39:13.581346, 2017-12-22 19:39:13.581346).\n"
```

Generated SQL with `defPPConfig` shows this:

```
CREATE TABLE IF NOT EXISTS "User"
  ( "id" INT PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE
  , "admin" BOOLEAN NOT NULL
  , "username" TEXT NOT NULL
  , "password" TEXT NOT NULL
  , "dateCreated" DATETIME NOT NULL
  , "dateModified" DATETIME NOT NULL
  )
```

`AUTOINCREMENT` should be `SERIAL` for PostgreSQL. I know that `defPPConfig` is more SQLite oriented but when I've looked at [`pgBackend` implementation](https://github.com/valderman/selda/blob/1f7a304d5ccd9d1f0e4dc1c7031bf1257f7f6141/selda-postgresql/src/Database/Selda/PostgreSQL.hs#L134) `AutoIncrement` is just filtered out which prevents me from inserting new rows to my database.

There should be a new version of [this function](https://github.com/valderman/selda/blob/a67832be54b3e2496fa37a070c3aae27774cbf3e/selda/src/Database/Selda/SQL/Print/Config.hs#L56) which will render `AutoIncrement` as `SERIAL`.

**Comment by reygoch** [comment]
Ok, I guess that problem is that my column should be of type `SERIAL` instead of `Int8`. But there is currently no way to define that if I go the generic route and want `Int` as my `id` type, right?

**Comment by phaazon** [comment]
The rest of API uses `BIGSERIAL` Why do you want `SERIAL` in the first place?

**Comment by valderman** [comment]
Fixed as a side effect of #63.

**Comment by reygoch** [comment]
@valderman I've just switched from my forked version to the lts-10.5 on stackage which has selda 0.1.12 and the problem is still there. Fields marked with `autoPrimaryGen` generate `Int8 NOT NULL` instead of `BIGSERIAL` so this should still be open.

Although, I'm getting this when checking for the dependencies with stack:

```
selda 0.1.12
selda-postgresql 0.1.7.1
```

So maybe `selda-postgresql` should be updated / version number changed for stackage to pick it up?

**Comment by phaazon** [comment]
Seems to be the last versions. My PR wasn’t targeting to solve this ticket, so maybe we should take more time seeing the trickiness of this one. :)

**Comment by phaazon** [comment]
Looks like it’s linked to `Generic` related code, right?

**Comment by reygoch** [comment]
@phaazon yes, I already did the dirty fix for my needs, but I'll try to make another pull request today. API is a bit limited here so the only option I had was to search and replace the string for now.

**Comment by valderman** [comment]
Just a heads up: this fix is now in `selda-0.1.12.1`/`selda-postgresql-0.1.7.2`.
